# Generated by Django 4.2.5 on 2023-10-12 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automoveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('valorMaoObra', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('taxId', models.CharField(max_length=30)),
                ('cellphone', models.CharField(max_length=30)),
                ('is_customer', models.BooleanField(default=False)),
                ('is_employee', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('automoveisFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automoveisFKManutencao', to='appAutomotiv.automoveis')),
                ('categoriaservicoFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoriaservicoFKManutencao', to='appAutomotiv.categoriaservico')),
                ('customUserFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customUserFKManutencao', to='appAutomotiv.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('codigoFabricante', models.CharField(max_length=200)),
                ('nomeFabricante', models.CharField(max_length=200)),
                ('valorCompra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valorVenda', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postoTrabalho', models.CharField(choices=[('posto1', 'posto1'), ('posto2', 'posto2')], max_length=100)),
                ('customUserFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customUserFKReservas', to='appAutomotiv.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formaPagamento', models.CharField(choices=[('pix', 'pix'), ('boleto', 'boleto'), ('cartão de crédito', 'cartão de crédito'), ('cartão de débito', 'cartão de débito'), ('Dinheiro em espécie', 'Dinheiro em espécie'), ('Transferência bancária', 'Transferência bancária')], max_length=100)),
                ('data', models.DateField(auto_now_add=True)),
                ('numeroNota', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pendente', 'pendente'), ('aprovado', 'aprovado'), ('recusado', 'recusado')], max_length=100)),
                ('valorDesconto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valorFinal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customUserFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customUserFKPagamento', to='appAutomotiv.customuser')),
                ('manutencaoFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencaoFKPagamento', to='appAutomotiv.manutencao')),
            ],
        ),
        migrations.AddField(
            model_name='manutencao',
            name='produtosFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtosFKManutencao', to='appAutomotiv.produtos'),
        ),
    ]
