# Generated by Django 4.2.5 on 2023-10-15 00:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appAutomotiv', '0002_customuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='data',
            field=models.DateField(default=datetime.date(2023, 10, 14)),
        ),
        migrations.AddField(
            model_name='reservas',
            name='manutencaoFK',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='manutencaoFKReservas', to='appAutomotiv.manutencao'),
            preserve_default=False,
        ),
    ]
